# Site settings
title: Longboard výlety
email: vylety@rooland.cz
description: > # this means to ignore newlines until "baseurl:"
  Můj meetpoint s Pražskými Longboardaři.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: lipoqil
github_username:  roolo

# Build settings
markdown: kramdown

exclude: [CNAME, config.ru, Gemfile, Gemfile.lock, config.ru, public, Rakefile.rb, README, spec, tasks, tmp, Makefile]
